### ISSUE TITLE
MemoryError on read is not handled gracefully

### ISSUE THREAD

**Issue by bobveringa** [peterhinch/micropython-mqtt#151]
When receiving a lot of data, the `_as_read` function tries to allocate a byte array at [line 222](https://github.com/peterhinch/micropython-mqtt/blob/master/mqtt_as/__init__.py#L222) for the incoming size. If the broker sends a big package, this can cause a memory error. This memory error is not handled anywhere, and it results in the following behaviour.

`._as_read()` throws a memory error. This is not handled within this function. Then it goes to `.wait_msg()`, this also does not handle the memory error. And finally, `._handle_msg()` also does not handle it. The MemoryError then causes this whole task to crash. 

As a result of the `._handle_msg()` task crashing. Incoming messages are no longer handled. This results in `last_rx` not being updated anymore. And after a while, the `_keep_alive()` function determines that something is not right and starts a reconnect. This behaviour is hard to understand and difficult to track down.

There are a couple of options to improve this behaviour. One of these is that the `_handle_msg()` task also handles MemoryError exceptions. Maybe in these cases something should be logged instead of just the `pass` statement for OSErrors. By handling the MemoryError here, a reconnect is started explicitly, instead of it just happening because something crashes.

We tried some other solutions too, like trying to keep the connection alive, but this all adds a lot of complexity.

**Comment by peterhinch** [comment]
I don't believe there is a workable way to recover from memory errors. I've yet to encounter anyone who's achieved this.

In my experience the only solution is to stop them happening in the first place. Options are precompiling, freezing bytecode or redesigning the code to use less RAM. Periodically issuing `gc.collect()` helps avoid fragmentation and can stave off memory errors, see our `._memory` method. There is a YouTube video by Damien on optimising micropython which you might want to watch if you haven't already.

**Comment by bobveringa** [comment]
I don't entirely agree. The memory error on read is caused by the broker sending a packet that is too big. Regardless of the optimizations that we do, allocating 10k bytes (continuous) is likely to cause issues on many systems. We are already doing heavy memory optimizations and spend as significant number of resources on preventing heap fragmentation. I do agree that preventing memory errors is the best course of action; however, it is not always possible.

We are unfortunately not in a position to change what the broker is sending us. And it is reasonable to expect that people trying things out might also experiment with sending various packet sizes to the clients. 

What I am suggesting is just that *if* a memory error happens, it is handled more gracefully and recovery is faster. Currently, it depends on when the timeout is triggered and recovery can take around 2 minutes (4 * ping time). 

Just immediately reconnecting after a memory error does not really change the behavior, it just makes it more explicit and faster. This solution also how a low impact on complexity and memory usage.

**Comment by peterhinch** [comment]
Re allocating large buffers I have experience of this in my graphics work. The best solution is to pre-allocate the buffer early in the application loading. Allocating them at runtime is very hazardous. My GUI libraries can run with a frame buffer much bigger than 10KiB, but it is allocated as soon as possible before the main module is even compiled.

I haven't considered how this might be applied to `mqtt_as` - I'll give it some thought, but my time this week is limited - so I thought I'd prompt you with the idea.

**Comment by bobveringa** [comment]
I entirely agree, if at all possible, we try to avoid allocating large amounts of memory at runtime. To this extent, we have had discussions at the office regarding maybe assigning `mqtt_as` a pool of pre-allocated memory it can use instead of trying to allocate dynamically. We worked out some of the challenges with this approach and each time we do this, we quickly come to the realization that there are other options we can take that accomplish the same or at least similar goals.

The challenges we have identified so far are:
* Essentially writing a memory management system
   - How strict is pool usage going to be. Should all the bytes read be done with the pool? That is maybe a bit too much. But where do we draw the line?
* Even with all the locks, it is unclear what the impact of using a pre-allocated buffer. We use a lot of memory views and if the data changes, well... that is not desired.
* Performance impact (this could be either positive or negative)

Ideally, we would have more control over how (at least large buffers) are allocated to avoid more fragmentation. But the amount of effort needed to get to that level is not insignificant.

For now, we are handling Memory Errors in our application as described in the earlier post, which at least makes system behaviour a lot more predictable.

**Comment by peterhinch** [comment]
I don't have a problem with the idea of trapping memory errors as you describe.

I am alarmed by a system that can demand large and variable amounts of contiguous RAM at run time.

I assume that the problem here is that you may have multiple concurrent instances of `._as_read`. Constructing a pool is unlikely to be easy, and you run the risk of the pool suffering from fragmentation. A defragmentation process implies horrible difficulties with locks and pointers. I'll think about this further, but I suspect that this may be pushing a bare metal (or near bare metal) port of MP beyond its limits.

I assume that hardware solutions are out of the question - like adding a large [spiram chip](https://github.com/peterhinch/micropython_eeprom/blob/master/spiram/SPIRAM.md).

**Comment by bobveringa** [comment]
It is unfortunately not possible to add a large spiram chip.

I'll provide some context as to why this is happening. There are rarely memory errors in our application, but there are a few very specific instances. Some sensors on our board are running their own firmware that sometimes needs to be updated. This means sending binaries to the device. There is not enough memory to have both an SSL connection with the broker and an SSL connection to download new firmware over HTTPS (not using SSL is not an option). This means that we are downloading these updates over MQTT.

AWS IoT has some existing solutions for this that work well with our existing infrastructure. Basically, you can stream files from private resources to your devices over MQTT. It sends chunks of 4096 bytes encoded with base64 in a JSON field. So we have to allocate a buffer of 4096 bytes and then around 5500-ish bytes for the incoming messages. 

This buffer of 4096 bytes is pre-allocated. But because we are receiving between 20–30 chunks of data, each time those 5500 bytes are allocated dynamically, and sometimes this causes issues. To optimize memory, this process already uses custom written higher optimized methods to select the right JSON field and base64 decode things with basically no memory usage. The process is as optimized as it is going to get.

I understand that this is a very, very niche use case, and that it is unlikely that there are many other people pushing things to this extreme.

**Comment by peterhinch** [comment]
A possible option - I'm not sure whether this might help or not.

Add a `readinto` option here
```py
    async def _as_read(self, n, sock=None):  # OSError caught by superclass
        if sock is None:
            sock = self._sock
        data = bytearray(n) if isinstance(n, int) else n  # Allow a buffer to be passed
```
The problem presumably only occurs [in line 677](https://github.com/peterhinch/micropython-mqtt/blob/c444a4ee5b11d4ca222013ef4836ed44c2ddcfba/mqtt_as/__init__.py#L677) i.e. when a message read is known to be taking place. If there is a circumstance where concurrent message reads occur, is it permissible use a `Lock` to break the concurrency? If so, it would be possible to assign the memory from a pre-allocated buffer
```py
async with read_lock():
    msg = await self._as_read(mv_buffer[:sz])  # Memoryview into a pre-allocated buffer
```
This allows other `_as_read` operations to run concurrently, with the interlock restricted to incoming messages.

**Comment by peterhinch** [comment]
On reflection we may be overcomplicating this by assuming concurrent incoming messages. There is one broker and one socket, so just a single input stream. Only one instance of `.wait_msg` runs at any time. So there is no concurrency of incoming messages.

To put this another way, if the broker attempted to send two MQTT packets on the same stream, it would be impossible for the client to decode the incoming data. There is no need for `read_lock` and [line 677](https://github.com/peterhinch/micropython-mqtt/blob/c444a4ee5b11d4ca222013ef4836ed44c2ddcfba/mqtt_as/__init__.py#L677) could be repaced with
```py
msg = await self._as_read(mv_buffer[:sz])  # Memoryview into a pre-allocated buffer
```
However this lack of concurrency could (and probably should) be taken further, with **all** `._as_read` calls using the buffer. The purpose of the asynchronous read is to allow a long read operation to proceed concurrently with other tasks, but not with other calls to `._as_read` because these will not occur. 

On this basis, assuming there a buffer named `self.ip_buffer`, the only change to the code wold be
```py
    async def _as_read(self, n, sock=None):  # OSError caught by superclass
        if sock is None:
            sock = self._sock
        buffer = memoryview(self.ip_buffer)
```
The `._as_read` code would be unchanged from that published.

**Comment by bobveringa** [comment]
Concurrency should indeed not be an issue. 

But if `._as_read` returns a `memoryview` instead of a `bytearray` that would probably be a breaking change. Because currently, the `msg`  that is used in callbacks and events is the direct result of the `._as_read` method. People who are decoding this bytearray to a string using `.decode('utf-8')` will get errors. The fix for this is simple. just replace the decode with `str(msg, encoding='utf-8')` instead.

```python
        msg = await self._as_read(sz)
        retained = op & 0x01
        if self._events:
            if self.mqttv5:
                self.queue.put(topic, msg, bool(retained), decoded_props)
            else:
                self.queue.put(topic, msg, bool(retained))
```

I just discussed this with my colleague, and we think that using a pre-allocated buffer would likely solve a lot of the problems we are having, as well as just generally reducing memory fragmentation.

If you are interested in adding this functionality to this library, we can spend the engineering time developing this feature. There are just some basic questions to answer.
* Is pre-allocated optional. (keeping dynamic allocation as the default would result in no breaking change for most users)
* If a message is bigger than the buffer (because a small buffer size is allocated) do we try to allocate it dynamically anyway (probably not a good idea to mix the 2 approaches)
* Is the pre-allocation a buffer that is passed to mqtt_as or is mqtt_as given a size of the buffer that should be created.
* If using a pre-allocated buffer and mqttv5 is the [Receive Maximum](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901049) property set on connect. (Should probably be up to the user)

**Comment by peterhinch** [comment]
I have pushed a branch `read_allocate`. Note this is untested. It suggests an approach. The read buffer is initially sized to a global constant `IBUFSIZE`. If an application knows it will get rare large messages, this can be increased to avoid late allocations.

If a message is too big for the buffer it is grown by an amount rather greater than is needed - this is to avoid lots of small allocations.

I hadn't spotted that problem with decoding.

**Comment by bobveringa** [comment]
Going through these code changes, it seems like an elegant way of doing things I hadn't thought of. 

We will test this out on some of our internal devices, and report back here.

**Comment by peterhinch** [comment]
Unfortunately there is a snag. Consider this user code:
```py
async def messages(client):
    async for topic, msg, retained in client.queue:
        asyncio.create_task(process_message(msg))
```
If two messages arrive in quick succession, two instances of `process_message` may be created. When the second message arrives, the first instance will see its data corrupted. This problem is likely to occur quite widely, when consecutive calls to `._as_read` occur - including within the client module itself.

I feel sure we can fix this problem, but the solution may need to be specific to your requirement rather than for the release code. My initial thoughts are that, for a practical API, copying must occur. This could be done higher up the call chain rather than in `._as_read`. This might allow an additional copy-free API - however the application would then have to deal with the above overrun possibility (in your application, is there a risk of overrun?).

As I mentioned before, I am very busy this week (a house full of visitors, including young grandchildren). However things will be back to normal on Friday so I'll be able to give this my full attention.

**Comment by bobveringa** [comment]
Your efforts are already greatly appreciated, and there is no haste with this issue. I have some holidays coming up myself but should be back around Tuesday–Wednesday.

We did some experiments with the `read_allocate` branch, and we found the following things. 

A typo [here](https://github.com/peterhinch/micropython-mqtt/blob/read_allocate/mqtt_as/__init__.py#L191). 

A minor thing, where currently `.as_read` returns a `memoryview`, but this is the size of the entire buffer. So converting this to a string (or just trying to compare) will run the entire length of the buffer. This is also a simple fix by just fixing the `return buffer[:n]` as this is already a `memoryview` no copies are made.

One of the bigger issues has to do with the way `._as_read` uses the buffer. It always starts at index 0 of the buffer. This is usually fine. Except when handling incoming publish packets. Because both the topic and msg are returned to the user. So a memoryview for the topic is returned, then some other calls to `._as_read` overwrite the first couple bytes of the topic, and finally the message overwrites all or most of the topic.

Here is what this would look like (These are not real topics and data, but more to show the error)
```
Expected topic:
sensors/some-things/other-things/rest-of/the-topic/json
Got:
{"a":4,"b":[{"c":0,"d":115932}]}/rest-of/the-topic/json
```

We tried playing around with passing an offset to the `._as_read` function. But this got complicated and unmanageable quickly. Eventually, we just decided to allocate a bytearray for the topic, as we were seeing some other weird effects we did not have the time to investigate yet. There are some options, like keeping track of the offset in `.as_read` or maybe some other way to keep track of it.

I've briefly looked at our risk of overrun, but it doesn't appear our application has a problem with this. It does all feel like a very solvable problem.

One thing to note is that once we set the `IBUFSIZE ` to a big number (like 5600), for some reason we were unable to start an SSL connection, and we kept getting MBED TLS errors. But this likely has some other cause, as there is more than enough memory available at this point. I have to investigate how and why this happens.

**Comment by peterhinch** [comment]
I have spent some time looking at the code and spotted that issue with `topic` and `msg`. I also am not keen on returning a `memoryview` as a message - I think breakages will extend beyond converting to Unicode.

At the moment I think the client needs two modes. In the normal mode a message is a copied bytes object, as at present. In the other mode, it is `memoryview` instance. A method call would switch modes.

Would such a solution be compatible with your needs?

**Comment by peterhinch** [comment]
Trying to think of a way forward, there are two issues
1. Fixing your specific problem.
2. Whether to change the published code.

I'd be grateful if you could indicate whether, in your application, you are happy with incoming messages always being a `memoryview` of the buffer.

Re the published code, I think returning a `memoryview` by default is a bad idea. I see three options:
1. Leave the code unchanged.
2. Use a buffer, but copy `msg` to a `bytes` object as per `topic`
3. Make the return type selectable as per [commented out code](https://github.com/peterhinch/micropython-mqtt/blob/798c56337e1fd27dfaa2e68b88115fecdceea106/mqtt_as/__init__.py#L682).

Option 2 offers reduced allocation but is a fairly radical change. I'd need to think carefully about possible unintended consequences. I will further review the code to see if there are other instances of scribbling like the `topic` problem.

Option 3 offers extra flexibility (and you might want to implement this for your application). However, as you pointed out, it is a niche requirement; one which has never arisen in the past.

**Comment by bobveringa** [comment]
In our application, a `memoryview` would not make a difference compared to a `bytearray`. While I agree that there are likely some unintended consequences, I also think that for most applications the impact will be low.

Built-in libraries like `json` handle a `memoryview` just fine. Looping over a `memoryview` is pretty much identical to looping over a `bytearray`. Index access has not changed. `len()` works the same. Comparisons between `memoryview` and `bytearray` also just work fine.

The big differences are that `.decode` does not exist on a `memoryview`, and that `print()` doesn't show the content of the `memoryview`.  This last one somewhat applies to `str()` too, but not in a super meaningful way.
```
>>> str(m)
'<memoryview>'
>>> str(b)
'bytearray(b\'{"a": [1, 2, 3, 4, 5, 6], "b": 10}\')'
```

That does not mean that this is a change that should be made without consideration, there are likely to be some edge cases. However, apart from the `.decode` function, I don't think this is likely to have a significant impact on many applications.

**Comment by bobveringa** [comment]
I'm currently on holiday. I'd have to investigate our options when I get back.

We are using the callback interface. And I am 90% sure all our calls are synchronous. 

I am back at work next Wednesday. I'd have to catch up with some other stuff first, but I should have an answer for you by Thursday.

**Comment by peterhinch** [comment]
I have pushed an update to the `read_allocate` branch. This has the following changes:
1. Add `v5/cbtest.py` test script for the callback interface.
2. Incoming messages are copied if the event issue is used (reason presented above).
3. If the callback interface is used, copying is determined by the global `MSG_BYTES=True`. If `False` a `memoryview` is returned.
4. The function `decode_properties` in `mqtt_v5_properties.py` now converts `memoryview` instances to bytes. Errors occurred if a `memoryview` was passed, and print statements produced unhelpful `<memoryview>` output..
5. `__init__py` has some minor refactoring to try to reduce code size.

I've spent some time considering what to do with the main branch. I'll report in a separate message.

**Comment by bobveringa** [comment]
Good to see these changes. I've looked out are code base and all our calls are indeed synchronous. My schedule is busier than I anticipated. So I don't think I'll have time this week to test out all these changes. I've added an item for me to take a decent amount of time and look into this next starting Wednesday (this is when our new sprint starts).

I am still having some weird issues with memory allocation, but I am not convinced that is caused by these changes. As said, I don't have the time to investigate this right now.

**Comment by bobveringa** [comment]
After spending most of my morning on this, I have not been able to fix the weird MBED_TLS errors that are thrown. It makes no sense to me why using this pre-allocated approach would have any negative effect on MBED_TLS.

We have decided to remove the code that is causing all these memory problems and migrate it to a new system.

Nevertheless, we still think that this pre-allocated approach is good to reduce memory fragmentation and generally improve performance. 

The updated version `read_allocate` seems to work well with our current software, even with `MSG_BYTES=False`. I did increase the size of `IBUFSIZE` as some of the messages our application gets at startup are way bigger than the 50 default start. Given that we always get these messages, it makes sense to just set this number higher.

As for how we are going to proceed with this update.
1. Migrate the code that is being difficult to the new system
2. Then switch over the `read_allocate`

**Comment by peterhinch** [comment]
The reason `MSG_BYTES` and `IBUFSIZE` are public is to enable them to be set by the application. If you are expecting large messages, I recommend setting - in the application - `IBUFSIZE` to at least the size of the largest expected message. This avoids late allocation and RAM errors. Obviously this must be done after import but before instantiating the client.

Have you proved that the MBEDTLS errors are associated with `read_allocate`? Please see [my other message](https://github.com/peterhinch/micropython-mqtt/issues/153#issuecomment-2346131000) - I'm struggling to understand the significance of this error.

**Comment by bobveringa** [comment]
I don't think `read_allocate` is the root cause of the problems. But doing a simple test using the version on `master` works without these issues, and then using the `read_allocate` branch causes MBEDTLS errors often. The MBEDTLS errors vary, but they all indicate that there is not enough memory for an SSL connection.

My best guess is that this has something to do with the available system memory and the way the MicroPython heap allocates it.

We looked at what it would take to "fix" that, and decided it was easier to migrate the problematic code to one of our other subsystems. We rather have the improvements that `read_allocate` brings than keep this problematic code.
